on: [push, pull_request]

name: Basic

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.46.0
          target: wasm32-unknown-unknown
          override: true

      - name: Run unit tests
        working-directory: ./secret-contracts/calculator-with-permits
        uses: actions-rs/cargo@v1
        with:
          command: unit-test
          args: --locked
        env:
          RUST_BACKTRACE: 1

      - name: Compile WASM contract
        working-directory: ./secret-contracts/calculator-with-permits
        uses: actions-rs/cargo@v1
        with:
          command: wasm
          args: --locked
        env:
          RUSTFLAGS: "-C link-arg=-s"

      - name: Run integration tests
        working-directory: ./secret-contracts/calculator-with-permits
        uses: actions-rs/cargo@v1
        with:
          command: integration-test
          args: --locked


  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        working-directory: ./secret-contracts/calculator-with-permits
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.46.0
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        working-directory: ./secret-contracts/calculator-with-permits
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        working-directory: ./secret-contracts/calculator-with-permits
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      # TODO: we should check
      # CHANGES_IN_REPO=$(git status --porcelain)
      # after this, but I don't know how
      - name: Generate Schema
        working-directory: ./secret-contracts/calculator-with-permits
        uses: actions-rs/cargo@v1
        with:
          command: schema
